title: imfeb / ER
description: February is a good month.

social:
  - title: Twitter
    img: /assets/images/twitter.ico
    url: https://twitter.com/imyyh
  - title: Github
    img: /assets/images/github.ico
    url: https://github.com/
  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:yangyonghong@gmail.com

avatar: /assets/images/imyyh.jpg
introduction: >
  The man has nothing to do and finds someting,but still has none.

working:
  title: Life Node
  timeline:
    - date: 1980-08
    - "Born in a small village and know sky is blue."
    - date: 1986-09
    - "Go to my kindergarten and learn how to play."
    - date: 1999-09
    - "My first University."
    - date: 2001-09
    - "My second University."
    - date: 2005-07
    - "End my road at school and have a job."
    - date: 2012-11
    - "Also have my own life home."
    - date: 2013-04
    - "End all in my own family life."
    - date: 2016-11
    - "Begin new life in ChongQing."
    - date: 2019-01
    - "Back to my good life city GuangZhou."
    - date: 2019-10
    - "My BRAIN is dead."
    - date: 2020-02
    - "Everything comes back to me and I have my new life."
