title: imfeb
description: One who is ER.

social:
  - title: Twitter
    img: /assets/images/twitter.ico
    url: https://twitter.com/imyyh
  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:yangyonghong@gmail.com

avatar: /assets/images/imyyh.jpg
introduction: >
  Hi! My nickname is imyyh.A man have nothing to do,always find something to do,but still have nothing to do.

working:
  title: Life Node
  timeline:
    - "Born and know nothing"
    - date: 1980-08
