title: imfeb / 二月
description: One who is ER.

social:
  - title: GitHub
    img: /assets/images/github.ico
    url: https://github.com/imyyh
  - title: Twitter
    img: /assets/images/twitter.ico
    url: https://twitter.com/imyyh
  - title: Douban
    img: /assets/images/douban.ico
    url: https://www.douban.com/people/imyyh
  - title: Weibo
    img: /assets/images/weibo.ico
    url: http://weibo.com/imyyh
  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:yangyonghong@gmail.com

avatar: /assets/images/imyyh.jpg
introduction: >
  Hi! My nickname is imyyh.
