title: imfeb / 二月
description: One who is ER.

social:
  - title: GitHub
    img: /assets/images/github.ico
    url: https://github.com/imyyh
  - title: Twitter
    img: /assets/images/twitter.ico
    url: https://twitter.com/imyyh
  - title: Weibo
    img: /assets/images/weibo.ico
    url: https://weibo.com/imyyh
  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:yangyonghong@gmail.com

avatar: /assets/images/imyyh.jpg
introduction: >
  Hi! My nickname is imyyh.

working:
  title: Life Node
  timeline:
    - date: Now
    - "To live"
    - date: 2013-04
    - "Just like that,I was in love with a girl"
    - date: 2002-02
    - "Blank days"
    - date: 2000-07
    - "Leave school after only one year"
    - date: 1999-09
    - "My school days"
    - date: 1987-09
    - "Born and know nothing"
    - date: 1980-08
