title: imfeb / ER
description: Feb is good month,So I am here.

social:
  - title: Twitter
    img: /assets/images/twitter.ico
    url: https://twitter.com/imyyh
  - title: Github
    img: /assets/images/github.png
    url: https://github.com
  - title: V2ex
    img: /assets/images/v2ex.png
    url: https://www.v2ex.com/
  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:yangyonghong@gmail.com

avatar: /assets/images/imyyh.jpg
introduction: >
  A man has nothing to do,always finding but still has none.

working:
  title: Life Node
  timeline:
    - date: 1980-08
    - "Born in a small village and know the sky is blue."
    - date: 1986-09
    - "Go to my kindergarten and learn how to play."
    - date: 2005-07
    - "End my school road and have a job."
    - date: 2012-11
    - "Also have my own family."
    - date: 2013-04
    - "End all in my own family life."
    - date: 2016-11
    - "Begin my CQ life."
    - date: 2019-01
    - "Back to my beautiful life city GZ."
    - date: 2019-10
    - "Because my BRAIN,I know nothing in the world."
    - date: 2021-02
    - "Everything comes back to me and I have my new life."
