title: imfeb / 二月
description: One who is ER.

social:
  - title: GitHub
    img: /assets/images/github.ico
    url: https://github.com/imyyh
  - title: Twitter
    img: /assets/images/twitter.ico
    url: https://twitter.com/imyyh
  - title: Weibo
    img: /assets/images/weibo.ico
    url: https://weibo.com/imyyh
  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:yangyonghong@gmail.com

avatar: /assets/images/imyyh.jpg
introduction: >
  Hi! My nickname is imyyh.

life:
  title: Life Node
  timeline:
    - date: Now
    - "Born and Live"
    - date: 1980-08
