title: imfeb / ER
description: One who is ER.

social:
  - title: Twitter
    img: /assets/images/twitter.ico
    url: https://twitter.com/imyyh
  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:yangyonghong@gmail.com

avatar: /assets/images/imyyh.jpg
introduction: >
  Hi! My nickname is imyyh.<br>
  A man has nothing to do,always finding but still has none.

working:
  title: Life Node
  timeline:
    - date: 1980-08
    - "Born in a small village and know nothing."
    - date: 1986-09
    - "Go to my first school and learn my life."
    - date: 1999-09
    - "My university life,but I don't like it,after one year I leave this school."
    - date: 2001-09
    - "My second university."
    - date: 2002-07
    - "I have my first love."
    - date: 2005-07
    - "Ending the road to school."
    - date: 2005-09
    - "Have my first job."
    - date: 2012-11
    - "Also have my own family."
    - date: 2014-04
    - "Change all my life,my life is over."
