title: imfeb / ER
description: One who is ER.

social:
  - title: Twitter
    img: /assets/images/twitter.ico
    url: https://twitter.com/imyyh
  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:yangyonghong@gmail.com

avatar: /assets/images/imyyh.jpg
introduction: >
  Hi! My nickname is imyyh.<br>
  A man has nothing to do,always finding,but still has none.

working:
  title: Life Node
  timeline:
    - date: 1980-08
    - "Born in a small village and know nothing."
    - date: 1986-09
    - "Go to my first school and learn my life."
    - date: 1999-09
    - "My university life,but I don't love it,after a year I left this school."
    - date: 2001-09
    - "My second universities."
    - date: 2005-07
    - "I have my first job,just a IT."
